nlp/urls.py
from django.urls import path
from . import views

app_name = 'nlp'

urlpatterns = [
    path("urlsummarizer/", views.urlsummarizer, name="urlsummarizer"),
    path("urlshowcase/", views.urlshowcase, name="urlshowcase"),
    path("paragraph/", views.paragraph, name="paragraph"),
    path("filesummarizer/", views.filesummarizer, name="filesummarizer"),

    # path("filemailtest/", views.filemailtest, name="filemailtest"),
]

summarizer/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from django.conf.urls import (handler400, handler403, handler404, handler500)

urlpatterns = [
    path('admin/', admin.site.urls),
    path("", include("users.urls")),
    path("nlp/", include("nlp.urls")),
]+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as auth_view
from django.conf.urls import (handler400, handler403, handler404, handler500)

# handler400 = 'app.views.bad_request'
# handler403 = 'app.views.permission_denied'
# handler404 = 'app.views.page_not_found'
# handler500 = 'users.views.server_error'

app_name = 'users'

urlpatterns = [
    path("", views.home, name="home"),
    path("register/", views.register, name="register"),
    path("profile/", views.profile, name="profile"),
    path("dictionary/", views.dictionary, name="dictionary"),
    path("about/", views.about_us, name="about"),
    path("login/", views.login_page, name="login"),
    path("logout/", auth_view.LogoutView.as_view(template_name="users/logout.html"), name="logout"),

]

# handler404 = "users.views.page_not_found_view"

users/models.py
from django.db import models

users/forms.py
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django import forms
from django.forms import ModelForm

class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ["username", "email", "password1", "password2"]

class LoginForm(forms.Form):
    username = forms.CharField(max_length=63)
    password = forms.CharField(max_length=63, widget=forms.PasswordInput)

users/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from .forms import UserRegisterForm, LoginForm
from django.contrib import messages
from django.contrib.auth.decorators import login_required

from django.views.generic.list import ListView
from django.urls import reverse
from multi_form_view import MultiModelFormView
from django.utils.crypto import get_random_string
from . models import *


def handle_server_error(request, exception=None):
    return render(request, "users/not_found.html")

def handle_page_not_found(request, exception=None):
    return render(request, "users/not_found.html")

def home(request):
    return render(request, "users/home.html")

@login_required
def profile(request):
    return render(request, "users/profile.html")

@login_required
def dictionary(request):
    return render(request, "users/summary/dictionary.html")

def about_us(request):
    return render(request, "users/about_us.html")

from django.contrib.auth import login, authenticate  # add to imports

def login_page(request):
    print("called loginform")
    form = LoginForm()
    message = ''
    if request.method == 'POST':
        print("inside post")
        form = LoginForm(request.POST)
        if form.is_valid():
           # check user exists
           print("form is valid")
           username=form.cleaned_data['username']
           user_exists = User.objects.filter(username=username).exists()
           print("line 48")
           if not user_exists:
               print("user doesnt exists")
               message = 'Invalid credentials !'
               return redirect("users:login")
           print("user exists   ")

           user = authenticate(username=form.cleaned_data['username'],password=form.cleaned_data['password'])
           # print("line 56")
           # print({user.username})
           # print({user.password})
           if user is not None:
               print({user.username})
               login(request, user)
               print("after login")
               message = f'Hello {user.username}! You have been logged in'
               return redirect("users:home")
           else:
               message = 'Login failed!'
               return redirect("users:login")


    return render(request, 'users/login.html', context={'form': form, 'message': message})

def register(request):
    if request.method == "POST":
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get("username")
            messages.success(request, f"Hi {username}, your account is created successfully.")
            return redirect("users:home")
    else:
        form = UserRegisterForm()
    return render(request, "users/register.html", {"form":form})

users/templates/users/about_us.html
{% extends 'users/base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="container fancy-bg">
  <div class="row">
    <h1 class="fancy-title">Automatic Text Summarization using Text Rank Algorithm</h1>
  </div>
  <div class="row">
    <div class="col-md-2">
      <h3>Algorithm</h3>
    </div>
    <div class="col-md-10">
      <h3>Text Rank Algorithm</h3>
    </div>
  </div>
  <div class="row">
    <h4>Features</h4>
    <ul>
      <li><h6>Paragraph Summarizer</h6></li>
      <li><h6>Document Summarizer</h6></li>
      <li><h6>URL Summarizer</h6></li>
      <li><h6>Portfolio Summarizer</h6></li>
      <li><h6>Dictionary</h6></li>
    </ul>
  </div>
  <div class="row">
    <h4>Research gap</h4>
    <ul>
      <li><h6>Single and document summarizer in one application itself</h6></li>
      <li><h6>Dictonary in order to grasp the best knowledge from summary</h6></li>
      <li><h6>Dataset named as glove.6B.100d is a word embedding's used for the vector representation of words </h6></li>
      <li><h6>User can compare the two summary of same topic but different input text and learn the best from it in very less time</h6></li>
    </ul>
  </div>


</div>
{% endblock %}

users/templates/users/base.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!--Css Style -->
    <link rel="stylesheet" href="{% static 'css/style.css' %}" type="text/css">
    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <!--Font Link-->
    <link rel="preconnect" href="https://fonts.gstatic.com">
    <link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@500&family=Open+Sans:wght@800&display=swap" rel="stylesheet">
      <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.6.1/css/all.css" integrity="sha384-gfdkjb5BdAXd+lj+gudLWI+BXq4IuLW5IT+brZEZsLFm++aCMlF1V92rMkPaX4PP" crossorigin="anonymous">
      <link rel="preconnect" href="https://fonts.googleapis.com">
 <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
 <link href="https://fonts.googleapis.com/css2?family=Roboto+Slab:wght@200;400&display=swap" rel="stylesheet">
<title>Summarizer</title>
  </head>
  <body id="bg">
  {% load static %}


        <header>
    <nav id="navbar">

        <ul>
        <li> <a href="{% url 'users:home' %}" class="" aria-current="page">Home</a></li>
         {% if user.is_authenticated %}
        <li> <a href="{% url 'nlp:paragraph' %}" class="">Paragraph</a></li>
        <li> <a href="{% url 'nlp:filesummarizer' %}" class="">Document</a></li>
        <li> <a href="{% url 'nlp:urlsummarizer' %}" class="">URL</a></li>
        <li> <a href="{% url 'nlp:urlshowcase' %}" class="">Portfolio</a></li>
        <li> <a href="{% url 'users:dictionary' %}" class="">Dictionary</a></li>
         {% endif %}
        <li> <a href="{% url 'users:about' %}" class="">About Us</a></li>
         {% if request.user.is_superuser %}
        <li> <a href="{% url 'admin:index' %}" class="" type="submit" id="header-links">Admin Dashboard</a></li>
         {% endif %}

        {% if user.is_authenticated %}
           <li><a href="{% url 'users:profile' %}" class="" type="submit" id="header-links"> Profile </a></li>
           <li><a href="{% url 'users:logout' %}" class="" type="submit" id="header-links"> Logout </a></li>
         {% else %}
           <li><a href="{% url 'users:register' %}" class="" type="submit" id="header-links"> Create Account </a></li>
           <li><a href="{% url 'users:login' %}" class="" type="submit" id="header-links">Log In</a></li>
           <li><a href="{% url 'admin:index' %}" class="" type="submit" id="header-links">Admin</a></li>
         {% endif %}
        </ul>

    </nav>
  </header>
        <div class="container">
          {% if messages %}
            {% for message in messages %}
              <div class="alert alert-{{message.tags}}">{{message}}</div>
            {% endfor %}
          {% endif %}
        </div>
        {% block content %}
        {% endblock content %}
        {% block dictionary %}
        {% endblock dictionary %}
      </div>

      <!-- Optional JavaScript; choose one of the two! -->

      <!-- Option 1: Bootstrap Bundle with Popper -->
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>

      <!-- Option 2: Separate Popper and Bootstrap JS -->
      <!--
      <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.1/dist/umd/popper.min.js" integrity="sha384-SR1sx49pcuLnqZUnnPwx6FCym0wLsk5JZuNx2bPPENzswTNFaQU1RDvt3wT4gWFG" crossorigin="anonymous"></script>
      <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.min.js" integrity="sha384-j0CNLUeiqtyaRmlzUHCPZ+Gy5fQu0dQ6eZ/xAww941Ai1SxSY+0EQqNXNE6DZiVc" crossorigin="anonymous"></script>
      -->
      <!-- <footer id="main-footer"> -->
   <!-- <p>Summary Project</p> -->
 <!-- </footer> -->
  </body>
</html>

users/templates/users/home.html
{% extends 'users/base.html' %}
{% load static %}
{% block content %}
<div class="container mt-5">
  {% if not user.is_authenticated %}
  <h3>Please <a href="{% url 'users:login' %}">login</a> to access this services.</h3>
  {% endif %}
    <div class="row">
      <div class="col-md-4">
          <div class="card p-3 bg-light">
              <div class="d-flex flex-row mb-3"><img src="https://img.icons8.com/external-flat-icons-inmotus-design/344/external-paragraph-internet-messenger-flat-icons-inmotus-design.png" width="70">
                  <div class="d-flex flex-column ml-2" style="margin:20px;">Paragraph Summarizer</div>
              </div>
              <h6>Copy and Paste the text and get the summary.</h6>
              {% if user.is_authenticated %}
              <div class="d-flex justify-content-between install mt-3"><a href="{% url 'nlp:paragraph' %}"><span class="text-primary">View&nbsp;<i class="fa fa-angle-right"></i></span></a></div>
              {% endif %}
          </div>
      </div>
      <div class="col-md-4">
          <div class="card p-3 bg-light">
              <div class="d-flex flex-row mb-3"><img src="https://img.icons8.com/clouds/344/file.png" width="70">
                  <div class="d-flex flex-column ml-2" style="margin:20px;">Document Summarizer</div>
              </div>
              <h6>Upload the file and get the summary of desired length of sentences.</h6>
              {% if user.is_authenticated %}
              <div class="d-flex justify-content-between install mt-3"><a href="{% url 'nlp:filesummarizer' %}"><span class="text-primary">View&nbsp;<i class="fa fa-angle-right"></i></span></a></div>
              {% endif %}
          </div>
      </div>
        <div class="col-md-4">
            <div class="card p-3 bg-light">
                <div class="d-flex flex-row mb-3"><img src="https://img.icons8.com/external-flaticons-flat-flat-icons/344/external-url-internet-marketing-service-flaticons-flat-flat-icons-2.png" width="70">
                    <div class="d-flex flex-column ml-2" style="margin:20px;">URL Summarizer</div>
                </div>
                <h6>Paste the Web page URL,click on genarte summary and get summary.</h6>
                {% if user.is_authenticated %}
                <div class="d-flex justify-content-between install mt-3"><a href="{% url 'nlp:urlsummarizer' %}"><span class="text-primary">View&nbsp;<i class="fa fa-angle-right"></i></span></a></div>
                {% endif %}
            </div>
        </div>

        <div class="col-md-6 py-3">
            <div class="card p-3 bg-light">
                <div class="d-flex flex-row mb-3"><img src="https://img.icons8.com/external-flaticons-lineal-color-flat-icons/344/external-services-car-wash-flaticons-lineal-color-flat-icons.png" width="70">
                    <div class="d-flex flex-column ml-2" style="margin:20px;">Portfolio</div>
                </div>
                <h6>Summary of latest technologies of 2022 and read its original article.</h6>
                {% if user.is_authenticated %}
                <div class="d-flex justify-content-between install mt-3"><a href="{% url 'nlp:urlshowcase' %}"><span class="text-primary">View&nbsp;<i class="fa fa-angle-right"></i></span></a></div>
                {% endif %}
            </div>
        </div>

        <div class="col-md-6 py-3">
            <div class="card p-3 bg-light">
                <div class="d-flex flex-row mb-3"><img src="https://img.icons8.com/color/344/dictionary.png" width="70">
                     <div class="d-flex flex-column ml-2" style="margin:20px;">Dictionary API</div>
                </div>
                <h6>To understand meaning of every word in summary.</h6>
                {% if user.is_authenticated %}
                <div class="d-flex justify-content-between install mt-3"><a href="{% url 'users:dictionary' %}"><span class="text-primary">View&nbsp;<i class="fa fa-angle-right"></i></span></a></div>
                {% endif %}
            </div>
        </div>

    </div>



{% endblock content %}

users/templates/users/login.html
{% extends 'users/base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block content %}
    <div class="container" style="margin-top: 30px;">
    <form action="" method="POST">
      {% csrf_token %}

      <div class="form-wrap">
        <h1>Sign In</h1>
        {{ form|crispy }}
        <button type="submit" class="btn btn-dark">Sign In</button>
        <p class="bottom-text">
          Don't have an account ?
          <a href="{% url 'users:register' %}">Sign Up</a>
        </p>
      </div>

    </form>
    </div>
{% endblock %}

users/templates/users/logout.html
{% extends 'users/base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block content %}
<div class="container">
  <h1>You have been logged out.</h1>
  <h5><a href="{% url 'users:login' %}">Login again</a></h5>
</div>
{% endblock %}

users/templates/users/not_found.html
{% extends 'users/base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block content %}
<div class="container">
  <h1>Page Not Found</h1>
  <h5><a href="{% url 'users:home' %}">Go to home</a></h5>
</div>
{% endblock %}

users/templates/users/profile.html
{% extends 'users/base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<div class="container">
  <h2>{{user.username}}</h2>
  <h2>{{user.email}}</h2>
</div>
{% endblock %}

users/templates/users/register.html
{% extends 'users/base.html' %}
{% load crispy_forms_tags %}
{% load static %}

{% block content %}
<div class="container" style="margin-top: 30px;">
  <form action="" method="POST">
    {% csrf_token %}
    <div class="form-wrap">
      <h1>Sign Up</h1>
      {{ form|crispy }}
      <button type="submit" class="btn btn-dark">Sign Up</button>
      <p class="bottom-text">
        Already have an account ?
        <a href="{% url 'users:login' %}">Sign In</a>
      </p>
    </div>
  </form>
</div>
{% endblock %}